name       : libfontenc
version    : 1.1.5
release    : 15
source     :
    - https://www.x.org/releases/individual/lib/libfontenc-1.1.5.tar.gz : 83f7a20f5afacb9cf0066b3db8016d59103143d97b8d5650b14986445be91db4
license    : MIT
summary    : X font encoding library
component  : xorg.library
description: |
    libfontenc is a library which helps font libraries portably determine and deal with different encodings of fonts.
builddeps  :
    - pkgconfig32(zlib)
    - pkgconfig(xproto)
emul32     : yes
setup      : |
    %configure  --disable-static
build      : |
    %make
install    : |
    %make_install
