name       : libfontenc
version    : 1.1.3
release    : 7
source     :
    - https://www.x.org/releases/individual/lib/libfontenc-1.1.3.tar.gz : 6fba26760ca8d5045f2b52ddf641c12cedc19ee30939c6478162b7db8b6220fb
license    :
    - MIT
summary    : X font encoding library
component  : xorg.library
builddeps  :
    - pkgconfig32(zlib)
    - xproto
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    libfontenc is a library which helps font libraries portably determine and deal with different encodings of fonts.
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
