name       : libfontenc
version    : 1.1.4
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libfontenc-1.1.4.tar.gz : 895ee0986b32fbfcda7f4f25ef6cbacfa760e1690bf59f02085ce0e7d1eebb41
license    : MIT
summary    : X font encoding library
component  : xorg.library
description: |
    libfontenc is a library which helps font libraries portably determine and deal with different encodings of fonts.
builddeps  :
    - pkgconfig32(zlib)
    - pkgconfig(xproto)
emul32     : yes
setup      : |
    %configure  --disable-static
build      : |
    %make
install    : |
    %make_install
